services:
  controlnet-preprocessor:
    image: public.ecr.aws/i0t3i1w9/controlnet-preprocessor:latest
    # runtime: nvidia
    # build:
    #   context: ./
    #   dockerfile: Dockerfile.base
    ports:
      - "1234:1234"
    environment:
      - HOST=*
      - PORT=1234
    # volumes:
    #   - ./models:/models
    