services:
  controlnet-preprocessor:
    image: shawndreamupai/controlnet-preprocessor:base
    # runtime: nvidia
    build:
      context: ./
      dockerfile: Dockerfile.base
    ports:
      - "2222:2222"
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./models:/models